on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

env:
  GO_VERSION: 1.17.6
  GO_RELEASER_VERSION: v1.3.1

jobs:
  build:
    name: Create Release
#    if: github.repository == 'cilium/cilium-cli'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579

      - name: Set up Go
        uses: actions/setup-go@424fc82d43fa5a37540bae62709ddcc23d9520d4
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Unshallow
        run: git fetch --prune --unshallow

      - name: Create release
        uses: goreleaser/goreleaser-action@v2
        with:
          version: ${{ env.GO_RELEASER_VERSION }}
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.CILIUM_GITHUB_TOKEN }}

#      - name: Send slack notification
#        if: ${{ !success() && (github.event_name == 'schedule' || github.event_name == 'push') }}
#        uses: 8398a7/action-slack@a74b761b4089b5d730d813fbedcd2ec5d394f3af
#        with:
#          status: ${{ job.status }}
#          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
#        env:
#          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}